version: '3.8'
services:

  db:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: valeevilja/gym_front:v1
    volumes:
      - ../gym-front/:/app/result_build/
    depends_on:
      - db
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - ./.env  

  backend:
    image: valeevilja/gym_back:v1
    restart: always
    volumes:
      - ./gym-back/src/app:/app/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./.env


volumes:
  postgres_volume: